### PR TITLE
Downgrade Chakra to 1.x.x for React 17 compatibility

### PR DESCRIPTION
**Pull request by craigmassie**
[Chakra 2.x requires React 18](https://chakra-ui.com/getting-started/migration), and unfortunately, isn't back-compatible. This repo doesn't seem to be making use of any Chakra 2.x specific features, but will crash due to some reference to `useSyncExternalStore` in Chakra. 

I've tested the changes with a React 17 repo that I'm working on (upgrading to React 18 would be a huge undertaking for us), and everything seems to be running smoothly.

Happy to discuss here if this makes sense! If not, I'm happy to keep this in a fork.

### CODE REVIEW

**Comment by ciminelli** [comment]
Thanks for the PR, @craigmassie! 

We're going to do some research on this to see if there are any important changes for the components we're using, check for other compatibility issues, and think about future updates. We're also going to do some testing to see if everything looks/works as expected on Chakra v1 with React 18 and other versions. At first glance, I see we'll need to replace `defineStyleConfig` with `extendTheme` but will see what else there is, if anything. Will get back to you soon.

**Comment by craigmassie** [comment]
@ciminelli Really appreciate it, thank you so much!

**Comment by craigmassie** [comment]
Not the primary issue with using csv-import-react, closing

**Comment by ciminelli** [comment]
@craigmassie what was the primary issue you encountered?

**Pull request closed without merging**
