### PR TITLE
Internationalization support

### PR DESCRIPTION
**Pull request by civan**
Proposed implementation:

- The importer has predefined languages but the consumer can still override these translations

```ts
const  customTranslations: {
    jp: {
      "Upload": "アップロード",
      "Browse files": "ファイルを参照",
    },
    pt: {
      "Upload": "Carregar",
      "Browse files": "Procurar arquivos",
    },
  }

<CSVImporter language="es" customTranslations={customTranslations}  ...props />

```

[Screencast from 03-08-2024 12:55:20 PM.webm](https://github.com/tableflowhq/csv-import/assets/68451/debc91c5-a330-4cdd-9662-187c7b112dba)

Related Issue:  #84

### CODE REVIEW

**Comment by kedrigen** [comment]
Hi,

Any idea when this will be merged?

**Comment by gabrielwiggert** [comment]
Hi! Awesome feature. Any estimate on the release?

**Review by ciminelli — APPROVED** [review]

**Comment by ciminelli** [comment]
@kedrigen @johnwards @gabrielwiggert this is now released and available with version `1.0.12`!

The documentation can be found here: https://github.com/tableflowhq/csv-import?tab=readme-ov-file#internationalization

**Comment by gabrielwiggert** [comment]
Awesome! Thank you so much.

Just one fix in the documentation:

<CSVImporter language="jp" **translations**={customTranslations}  ...props />

to

<CSVImporter language="jp" **customTranslations**={customTranslations}  ...props />

(The correct prop is **customTranslations** instead of **translations** ;) )

**Comment by ciminelli** [comment]
> Awesome! Thank you so much.
> 
> Just one fix in the documentation:
> 
> <CSVImporter language="jp" **translations**={customTranslations} ...props />
> 
> to
> 
> <CSVImporter language="jp" **customTranslations**={customTranslations} ...props />
> 
> (The correct prop is **customTranslations** instead of **translations** ;) )

Thanks! I noticed this too and updated the README after I merged the PR.

**Pull request merged**
